spring:
  messages:
    basename: i18n/messages
  redis:
#    cluster:
#      nodes:
#        - 192.168.14.231:6379
#        - 192.168.14.232:6379
#        - 192.168.14.233:6379
#    sentinel:
#      master:
#      nodes:
    host: ${REDIS_HOST:192.168.1.225}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:fuckuhacker}
    database: 0
    lettuce:
         pool:
            # 连接池最大连接数（使用负值表示没有限制） 默认 8
            max-active: 16
            #连接池中的最小空闲连接
            min-idle: 1
            # 连接池最大空闲连接数 默认 8
            max-idle: 8


  rabbitmq:
      host: ${RABBIT_MQ_HOST:192.168.1.225}
      port: ${RABBIT_MQ_PORT:5672}
      username: ${RABBIT_MQ_USERNAME:admin}
      password: ${RABBIT_MQ_PASSWORD:admin}
#  配置说明：
#  * 1、binders： 一组rabbitMQ的连接信息；
#  * 2、bindings：声明输入和输出通道的接口集合；
#  * 3、input、output，stream提供的默认生产者与消费者；
#  * 4、destination要绑定的交换机，对应rabbitmq中的Exchanges。
#  * 5、group对应rabbitmq中的queue；
  cloud:
      stream:
        bindings:
          orderInput:
            destination: order
            #default-binder: de1faultRabbit
            group: test
          orderOutput:
            destination: order
          backInPut:
            destination: backtopic
            group: ss
            #default-binder: de1faultRabbit
          backOutPut:
            destination: backtopic

            #default-binder: de1faultRabbit
            #group: test
#        binders:
#          de1faultRabbit:
#            type: rabbit
#            environment:
#              spring:
#                rabbitmq:
#                  host: 192.168.1.225
#                  port: 5672
#                  username: admin
#                  password: admin
#                  virtual-host: /

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis.springdata
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java

#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${REDIS_HOST:192.168.1.225}
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:fuckuhacker}
#      database: 1




  # Redisson settings

  #path to config - redisson.yaml
 # spring.redis.redisson.config=classpath:redisson.yaml